# Optuna Hyperparameter Tuning Configuration for LightGBM

n_trials: 50

params:
  n_estimators:
    low: 200
    high: 2000
  learning_rate:
    low: 0.01
    high: 0.2
    log: true
  num_leaves:
    low: 20
    high: 150
  max_depth:
    low: 5
    high: 20
  reg_alpha: 
    low: 0.00000001
    high: 10.0
    log: true
  reg_lambda: 
    low: 0.00000001
    high: 10.0
    log: true
  colsample_bytree:
    low: 0.6
    high: 1.0
  subsample:
    low: 0.6
    high: 1.0